### PR TITLE
chore: Mobile Drivers License (mDL) context

### LINKED ISSUE #35: Mobile Drivers Licence (mDL) context

### PR DESCRIPTION
**Pull request by rolsonquadras**
closes #35 

Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>

### CODE REVIEW

**Comment by rolsonquadras** [comment]
Sample VC:

```
{
    "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https://raw.githubusercontent.com/rolsonquadras/context/issue-35/mDL/v1.jsonld"
    ],
    "credentialSubject": {
        "birthdate": "1993-12-05",
        "document_number": "S9OBVU5HAS2MXFJ",
        "driving_privileges": [
            "Car"
        ],
        "expiry_date": "2025-05-26",
        "family_name": "Doe",
        "given_name": "John",
        "issue_date": "2020-05-27",
        "issuing_authority": "Ontario Ministry Of Transport",
        "issuing_country": "CA",
        "type": "mDL"
    },
    "id": "http://example.com/e0368452-9fa4-4b2a-b008-a9fdb3430c65",
    "issuanceDate": "2020-08-11T16:48:54.7042751Z",
    "issuer": {
        "id": "did:trustbloc:testnet.trustbloc.local:EiBsKZtIjNljW6mdj1--XB46G96nkOW3dhGuk8h3x25wgg",
        "name": "trustbloc-ed25519signature2018-ed25519"
    },
    "proof": {
        "created": "2020-08-12T19:40:08.5139944Z",
        "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..lL8kidF2vjk8uM3tiHmjsh6JvoCL6lun8lYkbLjBHk31xlwiW-_u9BZ9DoDKkGtzB3QDrWbkNfVTtYq4194fBQ",
        "proofPurpose": "assertionMethod",
        "type": "Ed25519Signature2018",
        "verificationMethod": "did:trustbloc:testnet.trustbloc.local:EiBMZr24laluTrahqGmwCEEb9oTnxFq141-DmS4cDHmIMw#gyeyKTd2QqVVhuntCTNT"
    },
    "type": [
        "VerifiableCredential",
        "mDL"
    ]
}
```

**Comment by llorllale** [comment]
@rolsonquadras please link to the spec

**Comment by rolsonquadras** [comment]
> @rolsonquadras please link to the spec

@mavarley can you provide the public link for the spec ?

**Comment by rolsonquadras** [comment]
Related issues #40, #41 and #42.

**Comment by mavarley** [comment]
Which spec? There is no working draft of a Verifiable Credential for mDL. The current mDL spec is defined in ISO 18013.

**Comment by llorllale** [comment]
Link: file:///tmp/mozilla_llorllale0/ISO-IECJTC1-SC17-WG10_N1818_ISO_IEC_DIS_18013-5_E.pdf

**Comment by llorllale** [comment]
Link: https://isotc.iso.org/livelink/livelink?func=ll&objId=20919524&objAction=Open

**Comment by mavarley** [comment]
I would suggest we change the name from 'mDL' to 'mDLdemo' or something similar. "mDL" is a defined Standard term in the ID industry and we are not trying to propose this as a Standard -  this is for our demo purposes only (closely aligned on what we think the Standard may eventually look like).

**Comment by rolsonquadras** [comment]
> I would suggest we change the name from 'mDL' to 'mDLdemo' or something similar. "mDL" is a defined Standard term in the ID industry and we are not trying to propose this as a Standard - this is for our demo purposes only (closely aligned on what we think the Standard may eventually look like).

@mavarley May be I can move this to [/examples](https://github.com/trustbloc/context/tree/master/vc/examples) folder, so that we are clear about the status of this credential (that it's an example and not a standard). Let me know what you think. If this doesn't work, I can rename the type as you suggested.

**Comment by mavarley** [comment]
> @mavarley May be I can move this to [/examples](https://github.com/trustbloc/context/tree/master/vc/examples) folder, so that we are clear about the status of this credential (that it's an example and not a standard). Let me know what you think. If this doesn't work, I can rename the type as you suggested.

Ok I'll let you decide based on the following criteria:
1. If we intend to keep this definition in sync with an emerging Standard as it develops (whenever that is...), then drop it in /examples
2. If we just need this for a few short-term demos and plan on abandoning it when a Standard starts to develop, then rename it

I think the answer is (1 -we will try and keep it current) but I'll let the team decide.

Thanks!

**Comment by rolsonquadras** [comment]
> > @mavarley May be I can move this to [/examples](https://github.com/trustbloc/context/tree/master/vc/examples) folder, so that we are clear about the status of this credential (that it's an example and not a standard). Let me know what you think. If this doesn't work, I can rename the type as you suggested.
> 
> Ok I'll let you decide based on the following criteria:
> 
> 1. If we intend to keep this definition in sync with an emerging Standard as it develops (whenever that is...), then drop it in /examples
> 2. If we just need this for a few short-term demos and plan on abandoning it when a Standard starts to develop, then rename it
> 
> I think the answer is (1 -we will try and keep it current) but I'll let the team decide.
> 
> Thanks!

I too feel #1 would be better. It'll force us to be upto date with the standard as well.

@mavarley I have moved to /examples folder.

**Pull request merged**
